---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release
inputs:
  - name: bosh-cpi-src
  - name: ci
  - name: version-semver
outputs:
  - name: candidate
run:
  path: ci/ci/tasks/build-candidate.sh
