---
platform: linux
inputs:
  - name: bosh-docker-cpi-release
  - name: bosh-docker-cpi-release-ci
  - name: bosh-deployment
  - name: bosh-cpi-dev-artifacts
  - name: stemcell
run:
  path: bosh-docker-cpi-release-ci/ci/tasks/integration-test.sh
