---
name: ((deployment_name))

update:
  canaries: 0
  canary_watch_time: 1000-60000
  max_in_flight: 100%
  update_watch_time: 1000-60000

instance_groups:
  - name: test-instance
    azs:
      - z1
    instances: 1
    networks:
      - name: default
    stemcell: noble
    vm_type: default
    jobs:
      - name: bosh-dns
        release: bosh-dns
        properties:
          configure_systemd_resolved: true
          disable_recursors: true
          override_nameserver: false
          api:
            client:
              tls: ((dns_api_client_tls))
            server:
              tls: ((dns_api_server_tls))
      - name: post-deploy-script
        release: os-conf
        properties:
          script: |-
            #!/bin/bash
            echo success

releases:
  - name: bosh-dns
    url: "https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release"
    version: latest
  - name: os-conf
    url: "https://bosh.io/d/github.com/cloudfoundry/os-conf-release"
    version: latest

stemcells:
  - alias: noble
    os: ubuntu-noble
    version: latest

variables:
  - name: dns_api_tls_ca
    type: certificate
    options:
      common_name: dns-api-tls-ca
      is_ca: true

  - name: dns_api_server_tls
    type: certificate
    options:
      alternative_names:
        - api.bosh-dns
      ca: dns_api_tls_ca
      common_name: api.bosh-dns
      extended_key_usage:
        - server_auth

  - name: dns_api_client_tls
    type: certificate
    options:
      alternative_names:
        - api.bosh-dns
      ca: dns_api_tls_ca
      common_name: api.bosh-dns
      extended_key_usage:
        - client_auth
