---
platform: linux
inputs:
  - name: bosh-cpi-src
  - name: bosh-cpi-release
  - name: ci
  - name: release-version-semver
  - name: stemcell
outputs:
  - name: promoted
run:
  path: ci/ci/tasks/promote-candidate.sh
params:
  release_blobs_access_key: replace-me
  release_blobs_secret_key: replace-me
