---
# Configure Docker CPI agent blobstore options to match director's blobstore
- type: replace
  path: /instance_groups/name=bosh/properties/docker_cpi/agent/blobstore?
  value:
    provider: dav
    options:
      endpoint: https://((internal_ip)):25250
      user: agent
      password: ((blobstore_agent_password))
      tls:
        cert:
          ca: ((blobstore_ca.certificate))